dist: focal
language: minimal
services:
  - redis
os: linux
before_install:
  - export PATH=~/.volta:~/.volta/bin/volta:$PATH
  - ls $HOME/.volta
  - which volta
  - curl https://get.volta.sh | bash
  - volta install node@15.6.0
  - volta install pnpm@5.15.1
  - pnpm config set store-dir ~/.pnpm-store
install:
  - pnpm --recursive install
script:
  - pnpm --recursive run test
after_success:
  - pnpm --recursive run coverage
cache:
  npm: false
  directories:
    - "~/.pnpm-store"
