dist: focal
language: minimal
env:
  global:
    - VOLTA_HOME=$HOME/.volta
    - PATH=$VOLTA_HOME:$VOLTA_HOME/bin/volta:$PATH
services:
  - redis
os: linux
before_install:
  - curl https://get.volta.sh | bash
  - volta install node@15.6.0
  - volta install pnpm@5.15.1
  - pnpm config set store-dir ~/.pnpm-store
install:
  - pnpm --recursive install
script:
  - pnpm --recursive run test
after_success:
  - pnpm --recursive run coverage
cache:
  npm: false
  directories:
    - "~/.pnpm-store"
