dist: focal
language: minimal
services:
  - redis
os: linux
env:
  global:
    - PATH=$HOME/.volta:$HOME/.volta/bin:$PATH
before_install:
  - curl https://get.volta.sh | bash
  - ls $HOME/.volta
  - which volta
  - volta install node@15.6.0
  - volta install pnpm@5.15.1
  - pnpm config set store-dir ~/.pnpm-store
install:
  - pnpm --recursive install
script:
  - pnpm --recursive run test
after_success:
  - pnpm --recursive run coverage
cache:
  npm: false
  directories:
    - "~/.pnpm-store"
    - "$HOME/.volta"
