version: "3.9"

networks:
  feather:

services:
  auth-server:
    build:
      context: .
      dockerfile: dockerFiles/AuthServer.Dockerfile
      network: host
    expose:
      - "80"
    depends_on:
      - redis-server
    networks:
      - feather
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  file-server:
    build:
      context: .
      dockerfile: dockerFiles/FileServer.Dockerfile
      network: host
    ports:
      - "80"
    expose:
      - "80"
    depends_on:
      - auth-server
      - redis-server
    networks:
      - feather
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  redis-server:
    build:
      context: .
      dockerfile: dockerFiles/Redis.Dockerfile
      network: host
    expose:
      - "6379"
    networks:
      - feather
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
