version: "3.9"

networks:
  feather-net:
    name: feather-net
    driver: bridge
services:
  auth-server:
    container_name: auth-server
    build:
      context: .
      dockerfile: dockerFiles/AuthServer.Dockerfile
      network: host
    expose:
      - "8080"
    environment:
      NODE_ENV: 'development'
      NODE_DEBUG: 'AuthServer*,LibAuthServer*'
      UWS_PORT: "8080"
      REDIS_HOST: "redis-server"
      REDIS_PORT: "6379"
    depends_on:
      - redis-server
    networks:
      - feather-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  token-server:
    container_name: token-server
    build:
      context: .
      dockerfile: dockerFiles/TokenServer.Dockerfile
      network: host
    ports:
      - 9090:9090
    environment:
      NODE_ENV: 'development'
      NODE_DEBUG: 'Lib*,Token*'
      CONTEXT: 'featheri'
      REDIS_HOST: "redis-server"
      REDIS_PORT: "6379"
      TTL: "3000"
      UWS_PORT: "9090"
    depends_on:
      - redis-server
    networks:
      - feather-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  file-server:
    container_name: file-server
    build:
      context: .
      dockerfile: dockerFiles/FileServer.Dockerfile
      network: host
    ports:
      - 9091:9091
    depends_on:
      - auth-server
      - redis-server
    networks:
      - feather-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  redis-server:
    container_name: redis-server
    build:
      context: .
      dockerfile: dockerFiles/Redis.Dockerfile
      network: host
    expose:
      - "6379"
    networks:
      - feather-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
